### ISSUE TITLE
Configuração do ambiente

### ISSUE THREAD

**Issue by joaovitor3** [fastPay-pi2/products-api#2]
Tarefas:
- [x] Dockerizar ambiente da API
- [x] Criar docker-compose com os serviços da API e do banco de dados

Critérios de aceitação:
- [x] Aplicação funcionar corretamente utilizando Docker

**Comment by cjjcastro** [comment]
tudo isso já está configurado na branch [master](https://github.com/fastPay-pi2/products-api)
