### ISSUE TITLE
Configuração de integração contínua

### ISSUE THREAD

**Issue by joaovitor3** [fastPay-pi2/products-api#3]
Tarefas:
- [x] Realizar mirror do repositório para o gitlab
- [x] Configurar arquivo .gitlab-ci.yml

Critérios de aceitação:
- [x] Pipeline ser executado corretamente no gitlab

**Comment by cjjcastro** [comment]
O mirror do repositorio no gitlab pode ser encontrado no link a seguir:
https://gitlab.com/fastpay-pi2/products-api/
